const items = [
    {
        id: 0,
        name: 'Cheese Ramen',
        leftItems: 11,
        desc: 'Lorem ipsum dolor sit amet consectetur adipisicing elit',
        price: 3,
        img: 'image-1.png',
    },
    {
        id: 1,
        name: 'Cheese Buldak Ramyun',
        leftItems: 20,
        desc: 'Lorem ipsum dolor sit amet consectetur adipisicing elit',
        price: 4,
        img: 'image-2.jpeg',
    },
    {
        id: 2,
        name: 'Seaweed',
        leftItems: 5,
        desc: 'Lorem ipsum dolor sit amet consectetur adipisicing elit',
        price: 1,
        img: 'image-3.jpeg',
    },
    {
        id: 3,
        name: 'Dried Fruit Banana Chip',
        leftItems: 15,
        desc: 'Lorem ipsum dolor sit amet consectetur adipisicing elit',
        price: 4,
        img: 'image-4.jpeg',
    },
    {
        id: 4,
        name: 'Dried Cheese',
        leftItems: 9,
        desc: 'Lorem ipsum dolor sit amet consectetur adipisicing elit',
        price: 2,
        img: 'image-5.jpeg',
    },
    {
        id: 5,
        name: 'Jelly Watermelon',
        leftItems: 4,
        desc: 'Lorem ipsum dolor sit amet consectetur adipisicing elit',
        price: 2,
        img: 'image-6.jpeg',
    },
]