const items = [
    {
        id: 0,
        name: 'T-shirt',
        leftItems: 11,
        desc: 'Lorem ipsum dolor sit amet consectetur adipisicing elit',
        price: 11,
        img: 'image-1.webp',
    },
    {
        id: 1,
        name: 'Notebook',
        leftItems: 20,
        desc: 'Lorem ipsum dolor sit amet consectetur adipisicing elit',
        price: 8,
        img: 'image-2.webp',
    },
    {
        id: 2,
        name: 'Hoodie',
        leftItems: 5,
        desc: 'Lorem ipsum dolor sit amet consectetur adipisicing elit',
        price: 20,
        img: 'image-3.webp',
    },
    {
        id: 3,
        name: 'Mug',
        leftItems: 15,
        desc: 'Lorem ipsum dolor sit amet consectetur adipisicing elit',
        price: 10,
        img: 'image-4.webp',
    },
    {
        id: 4,
        name: 'Mug',
        leftItems: 9,
        desc: 'Lorem ipsum dolor sit amet consectetur adipisicing elit',
        price: 11,
        img: 'image-5.webp',
    },
    {
        id: 5,
        name: 'T-shirt',
        leftItems: 4,
        desc: 'Lorem ipsum dolor sit amet consectetur adipisicing elit',
        price: 15,
        img: 'image-6.webp',
    },
]